### ISSUE TITLE
IDA 7.4 Python 3 support is broken

### ISSUE THREAD

**Issue by trou** [williballenthin/ida-netnode#10]
Hello,
thanks for ida-netnode, it's very useful for us in [BinCAT](https://github.com/airbus-seclab/bincat). As I'm working on python3 compat, I've noticed that the current version is definitely not working correctly (problems with IDA API, bytes, types, etc.).

The current WIP version, targeting both python 2 and 3, is here: https://github.com/airbus-seclab/bincat/blob/python3/python/idabincat/netnode.py but I've also forked the project if you want me to make a pull request.

I'm not 100% sure everything is working correctly yet.

**Comment by williballenthin** [comment]
hey @trou 

thanks for pointing this out! i'd be happy to accept a PR that targets both py2+3. this would be useful to a lot of people. i can help with testing once the PR is open.

**Comment by williballenthin** [comment]
@tmr232 can maybe also lend a hand with review and testing

**Comment by williballenthin** [comment]
v2.0.0 release and uploaded to pypi

should be good to go now
https://pypi.org/project/ida-netnode/2.0/
