### ISSUE TITLE
Use getblob/setblob for real arbitrary length data storage

### ISSUE THREAD

**Issue by nirizr** [williballenthin/ida-netnode#6]
[getblob](https://www.hex-rays.com/products/ida/support/sdkdoc/classnetnode.html#a23082c47f875a28c05661f1e2177e7a9) and [setblob](https://www.hex-rays.com/products/ida/support/sdkdoc/classnetnode.html#a51dfdbba5ec4644516b9a88b3c51e4c5) are implemented and supported API functions to store data above 4k bytes.

It is advised in IDA's SDK to use those APIs instead of implementing other solutions [here](https://www.hex-rays.com/products/ida/support/sdkdoc/netnode_8hpp.html):

> If you need to store objects bigger that MAXSPECSIZE, please note that there are high-level functions to store arbitrary sized objects in supvals. See setblog/getblob and other blob-related functions.

Using those APIs will benefit this repository tremendously, removing a lot of complicated edge cases and logic.

**Comment by williballenthin** [comment]
whoa, yes, this is much much better! i really appreciate that you reported this issue. should be a fairly quick fix, resulting in lots of deleted lines. good!

**Comment by williballenthin** [comment]
looks like `getblob` is not exported via IDAPython. might have to do some `ctypes` magic to invoke these routines.

```
Python>getblob
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'getblob' is not defined
Python>idc.getblob
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getblob'
Python>idaapi.getblob
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getblob'
Python>idautils.getblob
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getblob'
```

idasdk ctypes reference: http://www.hexblog.com/?p=695

**Comment by nirizr** [comment]
`getblob` and `setblob` are not module level methods. I'm might not have been clear enough.
Those are methods of the `netnode` object and should be used similarly to how `hashstr` and `hashset` are used (respectively).

**Comment by williballenthin** [comment]
(facepalm) yes, of course. thanks!

**Comment by nirizr** [comment]
happens to the best of us, glad I could help!

**Comment by williballenthin** [comment]
looking into implementation....

`get/setblob` accepts only a supval (integer) as a key. so if going to support string keys, will need to keep a mapping from string-key to int-key.

**Comment by williballenthin** [comment]
lookup algorithm:

  - if type(key) is integer
    - try to return netnode.getblob(key), else
    - try to return netnode.supval(key), else
    - raise KeyError
  - if type(key) is string
    - try to return netnode.getblob(netnode.hashval(key, MAPPING_INDEX), BLOB_INDEX)
    - try to return netnode.hashval(key), else
    - raise KeyError

**Comment by williballenthin** [comment]
need an int-key blobstore and a string-key blobstore. since we don't want string-keys colliding with int-keys when we implement a map from string-key to int-key. propose:

```
INT_KEYS_TAG = 'M'
STR_KEYS_TAG = 'N'
STR_TO_INT_MAP_TAG = 'O'
```

**Comment by nirizr** [comment]
Result's looking good! :)
